[tool.pytest.ini_options]
pythonpath = ["backend"]
asyncio_default_fixture_loop_scope = "function"

[tool.ruff]
line-length = 88
[tool.ruff.lint]
select = ["E", "F", "W", "C", "N", "Q", "B", "I"]
ignore = ["E501", "B008"]

[tool.ruff-formatter]
line-length = 88
